name: Compile ESP32-C3 sketch

on:
  push:
    paths:
      - '**.ino'
      - '.github/workflows/compile.yml'
  pull_request:
  workflow_dispatch:   # дозволяє запустити вручну з вкладки Actions

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile sketch for ESP32-C3
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32c3
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          libraries: |
            - name: FastLED
            - name: ArduinoFFT
          sketch-paths: |
            - ./Light_music
